Update links for Flow in documentation pages
astarte-platform/astarte_flow pull request #151
Opened 2023-04-11 15:04 UTC by matt-mazzucato

- update links to the source of each documentation page
- update link to the homepage of the component

2023-05-05 12:56 UTC, Pavinati approved these changes

2023-05-05 12:58 UTC, Pavinati approved these changes

2023-05-12 15:43 UTC, Annopaolo requested changes

2023-05-12 15:43 UTC, Annopaolo commented on mix.exs
> +      |> String.replace("master", "snapshot")
Use a module attribute (see https://github.com/astarte-platform/astarte-kubernetes-operator/pull/325#discussion_r1188392927)

2023-05-15 10:57 UTC, Annopaolo approved these changes

2023-05-15 12:15 UTC, rbino approved these changes

2023-05-15 12:15 UTC, merged